# Test configuration for Kafka Producer Demo
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Logging configuration for tests
logging:
  level:
    com.example.kafka: DEBUG
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.springframework.test: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Test-specific settings
management:
  endpoints:
    web:
      exposure:
        include: health,info
