# Spring Boot Application Configuration
spring:
  application:
    name: kafka-producer-demo

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Acknowledgment configuration
      acks: all # Wait for all replicas to acknowledge
      retries: 3

      # Batch configuration for performance
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

      # Serialization
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      # Additional producer properties
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        request.timeout.ms: 30000
        delivery.timeout.ms: 120000
        compression.type: snappy

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Logging Configuration
logging:
  level:
    com.example.kafka: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Application Info
info:
  app:
    name: Kafka Producer Demo
    description: Spring Boot application demonstrating Kafka producer with error handling
    version: 1.0.0
